name: MooCraft
main: ee.moo.moocraft.MooCraft
version: 0.0.1
website: http://github.com/tanelsuurhans
author: Tanel Suurhans
description:

commands:
    give:
        description: Give yourself or someone else items
        usage: /give [item] [amount] [player]

    teleport:
        aliases: tp
        description: Teleports yourself or someone else
        usage:  |
                Usage of /teleport:
                /teleport [player]
                /teleport [x:y:z]
                /teleport ground
                /teleport [player] [player]
                /teleport [player] [x:y:z]
                /teleport [player] ground

    time:
        description: Set or show the current server time
        usage:  |
                Usage of /time:
                /time - Displays server time
                /time day - Makes it daytime
                /time night - Makes it nighttime

    playerlist:
        aliases: pl
        description: Lists all online players

    location:
        aliases: loc
        description: Show players location
        usage:  |
                Usage of /location
                /location
                /location [player]

    config:
        description: save or load the configuration
        usage:  |
                Usage of /config
                /config save
                /config load
                /config get [key]

    fire:
        description: Enable or disable fire spread and burning
        usage:  |
                Usage of /fire
                /fire burn [enable|disable]
                /fire spread [enable|disable]
                /fire [enable|disable]
                /fire spread
                /fire burn
                /fire
    kick:
        description: Kick a player
        usage:  |
                Usage of /kick
                /kick [player]

    god:
        description: God mode
        usage:  |
                Usage of /god
                /god [player]
                /god [player] [enable|disable]
                /god list

    compass:
        description: Check your bearing
        usage: /compass - will yield your current bearing

    depth:
        description: Check your depth from the sealevel
        usage: /depth - will return your depth from sealevel

    memory:
        description: Check server memory consumption
        usage: /memory

    heal:
        description: Heal player
        usage:  |
                /heal
                /heal [player]

    kill:
        description: Kill player
        usage:  |
                /kill
                /kill [player]

    home:
        description: Set or teleport to home
        usage:  |
                /home - return to your home
                /home set - set your home to current location

    world:
        description: Manage worlds
        usage:  |
                /world create [normal|nether]
                /world delete
                /world list
                /world players

    travel:
        description: Travel to world
        usage:  |
                /travel [world name]
                /travel [world index]

    warp:
        description: Create a warp spot or teleport
        usage:  |
                /warp create name
                /warp private name
                /warp remove name
                /warp list
                /warp [name]

    spawn:
        description: spawn a mob or animal
        usage:  |
                /spawn [name]

