name: MooCraft
main: ee.moo.moocraft.MooCraftPlugin
version: 0.0.1
website: http://github.com/tanelsuurhans
author: Tanel Suurhans
description:

commands:
    give:
        description: Give yourself or someone else items
        usage: /give [item] [amount] [player]

    teleport:
        aliases: tp
        description: Teleports yourself or someone else
        usage:  |
                Usage of /teleport:
                /teleport [player]
                /teleport [x:y:z]
                /teleport [player] [player]
                /teleport [player] [x:y:z]

    time:
        description: Set or show the current server time
        usage:  |
                Usage of /time:
                /time - Displays server time
                /time day - Makes it daytime
                /time night - Makes it nighttime

    playerlist:
        aliases: pl
        description: Lists all online players

    location:
        aliases: loc
        description: Show players location
        usage:  |
                Usage of /location
                /location
                /location [player]

    config:
        description: save or load the configuration
        usage:  |
                Usage of /config
                /config save
                /config load
                /config get [key]

    fire:
        description: Enable or disable fire spread and burning
        usage:  |
                Usage of /fire
                /fire burn [enable|disable]
                /fire spread [enable|disable]
                /fire [enable|disable]
                /fire spread
                /fire burn
                /fire